# Generated by Django 5.2.3 on 2025-08-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='localion',
            new_name='location',
        ),
    ]
